# Generated by Django 4.2.30 on 2026-04-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('sender_phone', models.CharField(max_length=30)),
                ('sender_name', models.CharField(blank=True, max_length=120)),
                ('group_jid', models.CharField(blank=True, max_length=100)),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('media_url', models.URLField(blank=True)),
                ('is_authorized', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
