# Generated by Django 4.2.30 on 2026-04-28 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('operator_phone', models.CharField(blank=True, max_length=30)),
                ('operator_name', models.CharField(blank=True, max_length=120)),
                ('instruction', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('awaiting_conf', 'Awaiting Confirmation'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('final_answer', models.TextField(blank=True)),
                ('error_detail', models.TextField(blank=True)),
                ('iterations', models.IntegerField(default=0)),
                ('log_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('tool_name', models.CharField(max_length=80)),
                ('tool_input', models.JSONField(default=dict)),
                ('tool_output', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agent.agentrun')),
            ],
            options={
                'ordering': ['run', 'step_number'],
            },
        ),
    ]
