# Generated by Django 4.2.30 on 2026-04-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('description_text', models.TextField(blank=True)),
                ('canva_design_id', models.CharField(blank=True, max_length=200)),
                ('jpg_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
