# Generated by Django 4.2.30 on 2026-04-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('granted', 'Granted'), ('revoked', 'Revoked'), ('reactivated', 'Reactivated'), ('denied_grant', 'Grant Denied (not a core op)'), ('denied_message', 'Message Denied (unauthorized sender)')], max_length=20)),
                ('actor_phone', models.CharField(help_text='Who took/attempted the action.', max_length=30)),
                ('actor_name', models.CharField(blank=True, max_length=120)),
                ('target_phone', models.CharField(blank=True, max_length=30)),
                ('target_name', models.CharField(blank=True, max_length=120)),
                ('group_jid', models.CharField(blank=True, max_length=120)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_jid', models.CharField(db_index=True, max_length=120)),
                ('member_phone', models.CharField(db_index=True, max_length=30)),
                ('member_name', models.CharField(blank=True, max_length=120)),
                ('granted_by', models.CharField(help_text='Phone number of the core operator who granted access.', max_length=30)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by', models.CharField(blank=True, max_length=30)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Group Membership',
                'ordering': ['-granted_at'],
                'unique_together': {('group_jid', 'member_phone')},
            },
        ),
    ]
