# Generated by Django 4.2.30 on 2026-04-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound_reply', 'Inbound Auto-Reply')], max_length=20)),
                ('to_address', models.EmailField(max_length=254)),
                ('cc_addresses', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=255)),
                ('body_preview', models.TextField(blank=True)),
                ('template_used', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('error_detail', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
