# Generated by Django 4.2.30 on 2026-04-28 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVRankingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_requirements', models.TextField()),
                ('source_type', models.CharField(max_length=30)),
                ('source_path', models.CharField(max_length=500)),
                ('top_n', models.IntegerField(default=30)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('output_zip', models.CharField(blank=True, max_length=500)),
                ('total_cvs', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('candidate_name', models.CharField(blank=True, max_length=200)),
                ('match_score', models.IntegerField(default=0)),
                ('key_qualifications', models.TextField(blank=True)),
                ('rank', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='cv_module.cvrankingjob')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
