# Generated by Django 4.2.30 on 2026-04-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvcandidate',
            name='current_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cvcandidate',
            name='current_designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cvcandidate',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cvcandidate',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cvcandidate',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cvcandidate',
            name='relevant_industries',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='cvcandidate',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvcandidate',
            name='years_experience',
            field=models.IntegerField(default=0),
        ),
    ]
