# Generated by Django 4.2.30 on 2026-04-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operator_name', models.CharField(blank=True, max_length=120)),
                ('operator_phone', models.CharField(blank=True, max_length=30)),
                ('instruction_text', models.TextField()),
                ('task_type', models.CharField(choices=[('email_outbound', 'Email – Outbound'), ('email_inbound', 'Email – Inbound Reply'), ('cv_ranking', 'CV Ranking & Filtering'), ('job_post', 'Job Post Creation'), ('code_gen', 'Software Code Generation'), ('git_push', 'Git Push'), ('confirmation', 'Confirmation Request'), ('unknown', 'Unknown / Unclassified')], default='unknown', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected (Unauthorised)')], default='pending', max_length=20)),
                ('output_location', models.TextField(blank=True)),
                ('error_detail', models.TextField(blank=True)),
                ('llm_cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
